apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: sonu-self-learning-portal-deployment
  labels:
    app: sonu-self-learning-portal-label
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: sonu-self-learning-portal-label
  template:
    metadata:
      labels:
        app: sonu-self-learning-portal-label
    spec:
      containers:
        - name: sonu-self-learning-portal
          image: sonu-self-learning-portal:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1001 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: sonu-self-learning-portal-deployment
spec:
  selector:
    app: sonu-self-learning-portal-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1001
      targetPort: 1001